/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Agents {
  commission_type: string;
  commission_value: Numeric | null;
  created_at: Generated<Timestamp>;
  email: string | null;
  id: Generated<number>;
  is_active: Generated<boolean>;
  name: string;
  phone: string;
  station_id: number | null;
  updated_at: Generated<Timestamp>;
}

export interface AgentCommissions {
  agent_id: number;
  approved_at: Timestamp | null;
  approved_by_user_id: number | null;
  booking_id: number;
  cancelled_reason: string | null;
  commission_amount: Numeric;
  commission_number: string;
  commission_type: string;
  commission_value: Numeric | null;
  created_at: Generated<Timestamp>;
  created_by_user_id: number | null;
  id: Generated<number>;
  notes: string | null;
  paid_at: Timestamp | null;
  paid_by_user_id: number | null;
  payable_after: Generated<string>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface BookingItems {
  booking_id: number;
  created_at: Generated<Timestamp>;
  description: string;
  id: Generated<number>;
  quantity: Generated<Numeric>;
  unit: string | null;
  weight_tons: Numeric | null;
}

export interface BookingPricingSnapshots {
  agent_commission_estimate: Generated<Numeric>;
  booking_id: number;
  created_at: Generated<Timestamp>;
  estimated_fuel_cost: Generated<Numeric>;
  estimated_margin_amount: Generated<Numeric>;
  estimated_margin_percent: Generated<Numeric>;
  expected_liters: Generated<Numeric>;
  final_freight_rate: Generated<Numeric>;
  fuel_price_per_liter: Generated<Numeric>;
  fuel_price_snapshot_id: number | null;
  id: Generated<number>;
  internal_overhead_cost: Generated<Numeric>;
  pricing_source: Generated<string>;
  reserve_liters: Generated<Numeric>;
  suggested_freight_rate: Generated<Numeric>;
}

export interface Bookings {
  agent_id: number | null;
  approved_at: Timestamp | null;
  approved_by_user_id: number | null;
  booking_number: string;
  cancel_reason: string | null;
  cargo_description: string;
  cargo_weight_tons: Numeric | null;
  contract_id: number | null;
  created_at: Generated<Timestamp>;
  created_by_user_id: number | null;
  customer_id: number;
  delivery_due_date: Timestamp | null;
  destination_station_id: number;
  final_freight_rate: Generated<Numeric>;
  id: Generated<number>;
  origin_station_id: number;
  pickup_date: Timestamp | null;
  quantity: Numeric | null;
  required_vehicle_type_id: number;
  requires_rate_approval: Generated<boolean>;
  route_id: number | null;
  status: Generated<string>;
  tax_amount: Generated<Numeric>;
  total_customer_amount: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
}

export interface Cities {
  country: Generated<string>;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  province: string | null;
}

export interface ContractRates {
  base_freight_rate: Numeric;
  contract_id: number;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  is_active: Generated<boolean>;
  loading_charges: Generated<Numeric>;
  minimum_margin_percent: Generated<Numeric>;
  route_id: number;
  tax_percent: Generated<Numeric>;
  unloading_charges: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  vehicle_type_id: number;
}

export interface CustomerContracts {
  contract_number: string;
  created_at: Generated<Timestamp>;
  customer_id: number;
  end_date: Timestamp;
  fuel_adjustment_enabled: Generated<boolean>;
  fuel_adjustment_per_liter: Numeric | null;
  fuel_base_price: Numeric | null;
  id: Generated<number>;
  rate_model: Generated<string>;
  start_date: Timestamp;
  status: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface CustomerInvoices {
  balance_amount: Generated<Numeric>;
  booking_id: number;
  created_at: Generated<Timestamp>;
  created_by_user_id: number | null;
  customer_id: number;
  due_date: Timestamp | null;
  id: Generated<number>;
  invoice_date: Generated<Timestamp>;
  invoice_number: string;
  issued_at: Timestamp | null;
  notes: string | null;
  paid_amount: Generated<Numeric>;
  status: Generated<string>;
  subtotal_amount: Generated<Numeric>;
  tax_amount: Generated<Numeric>;
  total_amount: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
}

export interface CustomerPayments {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  customer_id: number;
  customer_invoice_id: number;
  id: Generated<number>;
  notes: string | null;
  payment_date: Generated<Timestamp>;
  payment_method: Generated<string>;
  payment_number: string;
  received_by_user_id: number | null;
  reference_number: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Customers {
  billing_address: string | null;
  contact_person: string;
  created_at: Generated<Timestamp>;
  customer_type: string;
  email: string | null;
  id: Generated<number>;
  is_active: Generated<boolean>;
  name: string;
  ntn: string | null;
  phone: string;
  strn: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DriverAdvances {
  advance_number: string;
  advance_type: Generated<string>;
  amount: Numeric;
  cancelled_reason: string | null;
  created_at: Generated<Timestamp>;
  created_by_user_id: number | null;
  driver_id: number;
  id: Generated<number>;
  issued_at: Timestamp | null;
  issued_by_user_id: number | null;
  master_trip_id: number;
  payment_method: Generated<string>;
  reason: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface DriverExpenses {
  amount: Numeric;
  approved_at: Timestamp | null;
  approved_by_user_id: number | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  driver_id: number;
  expense_type: Generated<string>;
  id: Generated<number>;
  incurred_at: Generated<Timestamp>;
  master_trip_id: number;
  reject_reason: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Drivers {
  address: string | null;
  cnic: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  is_active: Generated<boolean>;
  license_expiry: Timestamp | null;
  license_number: string | null;
  name: string;
  phone: string;
  updated_at: Generated<Timestamp>;
}

export interface DriverSettlements {
  cancelled_reason: string | null;
  created_at: Generated<Timestamp>;
  created_by_user_id: number | null;
  driver_id: number;
  finalized_at: Timestamp | null;
  finalized_by_user_id: number | null;
  id: Generated<number>;
  master_trip_id: number;
  paid_at: Timestamp | null;
  paid_by_user_id: number | null;
  payable_to_driver_amount: Generated<Numeric>;
  recoverable_from_driver_amount: Generated<Numeric>;
  settlement_number: string;
  status: Generated<string>;
  total_advance_amount: Generated<Numeric>;
  total_approved_expense_amount: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
}

export interface DriverVehicleAssignments {
  assignment_type: string;
  created_at: Generated<Timestamp>;
  driver_id: number;
  end_date: Timestamp | null;
  id: Generated<number>;
  is_active: Generated<boolean>;
  start_date: Timestamp;
  updated_at: Generated<Timestamp>;
  vehicle_id: number;
}

export interface DeliveryProofs {
  booking_id: number;
  created_at: Generated<Timestamp>;
  created_by_user_id: number | null;
  delivered_at: Generated<Timestamp>;
  goods_condition: Generated<string>;
  id: Generated<number>;
  master_trip_id: number | null;
  proof_image_urls: Generated<unknown>;
  proof_number: string;
  receiver_cnic: string | null;
  receiver_name: string;
  receiver_phone: string | null;
  remarks: string | null;
  trip_leg_id: number | null;
  updated_at: Generated<Timestamp>;
}

export interface FuelPriceSnapshots {
  created_at: Generated<Timestamp>;
  created_by_user_id: number | null;
  effective_at: Timestamp;
  fuel_type: string;
  id: Generated<number>;
  price_per_liter: Numeric;
  source: Generated<string>;
}

export interface FuelSlips {
  created_at: Generated<Timestamp>;
  driver_id: number;
  fuel_type: string;
  fuel_vendor_id: number;
  id: Generated<number>;
  liters: Numeric;
  master_trip_id: number | null;
  notes: string | null;
  odometer_reading: Numeric | null;
  price_per_liter: Numeric;
  rejected_reason: string | null;
  slip_date: Generated<Timestamp>;
  slip_number: string;
  station_name: string | null;
  status: Generated<string>;
  total_amount: Numeric;
  trip_leg_id: number | null;
  updated_at: Generated<Timestamp>;
  vehicle_id: number;
  verified_at: Timestamp | null;
  verified_by_user_id: number | null;
}

export interface FuelVendors {
  address: string | null;
  city: string | null;
  contact_person: string | null;
  created_at: Generated<Timestamp>;
  email: string | null;
  id: Generated<number>;
  is_active: Generated<boolean>;
  name: string;
  ntn: string | null;
  payment_terms_days: Generated<number>;
  phone: string | null;
  updated_at: Generated<Timestamp>;
}

export interface FuelVendorInvoices {
  balance_amount: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  created_by_user_id: number | null;
  due_date: Timestamp | null;
  fuel_vendor_id: number;
  id: Generated<number>;
  invoice_date: Generated<Timestamp>;
  invoice_number: string;
  notes: string | null;
  paid_amount: Generated<Numeric>;
  status: Generated<string>;
  total_amount: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  vendor_invoice_number: string | null;
}

export interface FuelVendorInvoiceItems {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  fuel_slip_id: number;
  fuel_vendor_invoice_id: number;
  id: Generated<number>;
}

export interface FuelVendorPayments {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  fuel_vendor_id: number;
  fuel_vendor_invoice_id: number;
  id: Generated<number>;
  notes: string | null;
  paid_by_user_id: number | null;
  payment_date: Generated<Timestamp>;
  payment_method: Generated<string>;
  payment_number: string;
  reference_number: string | null;
  updated_at: Generated<Timestamp>;
}

export interface MasterTrips {
  actual_start_at: Timestamp | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by_user_id: number | null;
  current_station_id: number;
  driver_id: number;
  id: Generated<number>;
  planned_start_at: Timestamp | null;
  start_station_id: number;
  status: Generated<string>;
  trip_number: string;
  updated_at: Generated<Timestamp>;
  vehicle_id: number;
}

export interface Permissions {
  created_at: Generated<Timestamp>;
  description: string | null;
  group_name: string;
  id: Generated<number>;
  key: string;
  label: string;
}

export interface RolePermissions {
  permission_id: number;
  role_id: number;
}

export interface Roles {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  is_system: Generated<boolean>;
  label: string;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface RouteFuelProfiles {
  created_at: Generated<Timestamp>;
  expected_liters: Numeric;
  id: Generated<number>;
  is_active: Generated<boolean>;
  notes: string | null;
  reserve_liters: Generated<Numeric>;
  route_id: number;
  updated_at: Generated<Timestamp>;
  vehicle_type_id: number;
}

export interface RouteOverheadProfiles {
  created_at: Generated<Timestamp>;
  depreciation_cost: Generated<Numeric>;
  empty_return_risk_cost: Generated<Numeric>;
  id: Generated<number>;
  insurance_tax_cost: Generated<Numeric>;
  is_active: Generated<boolean>;
  maintenance_cost: Generated<Numeric>;
  oil_service_cost: Generated<Numeric>;
  route_id: number;
  route_risk_cost: Generated<Numeric>;
  total_overhead: Generated<Numeric>;
  tyre_cost: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  vehicle_type_id: number;
  workshop_reserve_cost: Generated<Numeric>;
}

export interface Routes {
  created_at: Generated<Timestamp>;
  destination_station_id: number;
  distance_km: Numeric | null;
  estimated_duration_hours: Numeric | null;
  id: Generated<number>;
  is_active: Generated<boolean>;
  name: string;
  origin_station_id: number;
  road_condition: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Stations {
  address: string | null;
  city_id: number;
  code: string | null;
  contact_phone: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  is_active: Generated<boolean>;
  name: string;
}

export interface TripEvents {
  created_at: Generated<Timestamp>;
  created_by_user_id: number | null;
  description: string | null;
  event_type: string;
  id: Generated<number>;
  master_trip_id: number;
  station_id: number | null;
  title: string;
  trip_leg_id: number | null;
}

export interface TripLegBookings {
  allocated_weight_tons: Numeric | null;
  booking_id: number;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  trip_leg_id: number;
}

export interface TripLegs {
  actual_arrival_at: Timestamp | null;
  actual_departure_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  destination_station_id: number;
  id: Generated<number>;
  master_trip_id: number;
  origin_station_id: number;
  override_approved_by_user_id: number | null;
  override_driver_id: number | null;
  override_reason: string | null;
  override_vehicle_id: number | null;
  planned_departure_at: Timestamp | null;
  route_id: number;
  sequence_no: number;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface UserRefreshSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<number>;
  refresh_token_hash: string;
  revoked_at: Timestamp | null;
  user_id: number;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  is_active: Generated<boolean>;
  name: string;
  password_hash: string;
  phone: string | null;
  role_id: number;
  updated_at: Generated<Timestamp>;
}

export interface Vehicles {
  created_at: Generated<Timestamp>;
  current_station_id: number;
  fitness_expiry: Timestamp | null;
  fuel_card_number: string | null;
  id: Generated<number>;
  insurance_expiry: Timestamp | null;
  is_active: Generated<boolean>;
  registration_expiry: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  vehicle_number: string;
  vehicle_type_id: number;
}

export interface VehicleTypes {
  capacity_tons: Numeric | null;
  code: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  is_active: Generated<boolean>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  agent_commissions: AgentCommissions;
  agents: Agents;
  booking_items: BookingItems;
  booking_pricing_snapshots: BookingPricingSnapshots;
  bookings: Bookings;
  cities: Cities;
  contract_rates: ContractRates;
  customer_contracts: CustomerContracts;
  customer_invoices: CustomerInvoices;
  customer_payments: CustomerPayments;
  customers: Customers;
  driver_advances: DriverAdvances;
  driver_expenses: DriverExpenses;
  driver_settlements: DriverSettlements;
  delivery_proofs: DeliveryProofs;
  driver_vehicle_assignments: DriverVehicleAssignments;
  drivers: Drivers;
  fuel_price_snapshots: FuelPriceSnapshots;
  fuel_slips: FuelSlips;
  fuel_vendor_invoice_items: FuelVendorInvoiceItems;
  fuel_vendor_invoices: FuelVendorInvoices;
  fuel_vendor_payments: FuelVendorPayments;
  fuel_vendors: FuelVendors;
  master_trips: MasterTrips;
  permissions: Permissions;
  role_permissions: RolePermissions;
  roles: Roles;
  route_fuel_profiles: RouteFuelProfiles;
  route_overhead_profiles: RouteOverheadProfiles;
  routes: Routes;
  stations: Stations;
  trip_events: TripEvents;
  trip_leg_bookings: TripLegBookings;
  trip_legs: TripLegs;
  user_refresh_sessions: UserRefreshSessions;
  users: Users;
  vehicle_types: VehicleTypes;
  vehicles: Vehicles;
}
