/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Cities {
  country: Generated<string>;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  province: string | null;
}

export interface Stations {
  address: string | null;
  city_id: number;
  code: string | null;
  contact_phone: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  is_active: Generated<boolean>;
  name: string;
}

export interface DB {
  cities: Cities;
  stations: Stations;
}
