/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as VehicleTypesRouteImport } from './routes/vehicle-types'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as RouteOverheadProfilesRouteImport } from './routes/route-overhead-profiles'
import { Route as RouteFuelProfilesRouteImport } from './routes/route-fuel-profiles'
import { Route as FuelPricesRouteImport } from './routes/fuel-prices'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as ContractRatesRouteImport } from './routes/contract-rates'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesNewRouteImport } from './routes/vehicles.new'
import { Route as VehiclesIdRouteImport } from './routes/vehicles.$id'
import { Route as VehicleTypesNewRouteImport } from './routes/vehicle-types.new'
import { Route as VehicleTypesIdRouteImport } from './routes/vehicle-types.$id'
import { Route as TripsNewRouteImport } from './routes/trips.new'
import { Route as TripsIdRouteImport } from './routes/trips.$id'
import { Route as RoutesNewRouteImport } from './routes/routes.new'
import { Route as RoutesIdRouteImport } from './routes/routes.$id'
import { Route as RouteOverheadProfilesNewRouteImport } from './routes/route-overhead-profiles.new'
import { Route as RouteOverheadProfilesIdRouteImport } from './routes/route-overhead-profiles.$id'
import { Route as RouteFuelProfilesNewRouteImport } from './routes/route-fuel-profiles.new'
import { Route as RouteFuelProfilesIdRouteImport } from './routes/route-fuel-profiles.$id'
import { Route as PricingRouteEstimateRouteImport } from './routes/pricing.route-estimate'
import { Route as FuelPricesNewRouteImport } from './routes/fuel-prices.new'
import { Route as FuelPricesIdRouteImport } from './routes/fuel-prices.$id'
import { Route as DriversNewRouteImport } from './routes/drivers.new'
import { Route as DriversIdRouteImport } from './routes/drivers.$id'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as ContractsNewRouteImport } from './routes/contracts.new'
import { Route as ContractsIdRouteImport } from './routes/contracts.$id'
import { Route as ContractRatesNewRouteImport } from './routes/contract-rates.new'
import { Route as ContractRatesIdRouteImport } from './routes/contract-rates.$id'
import { Route as BookingsNewRouteImport } from './routes/bookings.new'
import { Route as BookingsIdRouteImport } from './routes/bookings.$id'
import { Route as AgentsNewRouteImport } from './routes/agents.new'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as VehiclesIdEditRouteImport } from './routes/vehicles.$id.edit'
import { Route as VehicleTypesIdEditRouteImport } from './routes/vehicle-types.$id.edit'
import { Route as TripsIdEditRouteImport } from './routes/trips.$id.edit'
import { Route as RoutesIdEditRouteImport } from './routes/routes.$id.edit'
import { Route as RouteOverheadProfilesIdEditRouteImport } from './routes/route-overhead-profiles.$id.edit'
import { Route as RouteFuelProfilesIdEditRouteImport } from './routes/route-fuel-profiles.$id.edit'
import { Route as FuelPricesIdEditRouteImport } from './routes/fuel-prices.$id.edit'
import { Route as DriversIdEditRouteImport } from './routes/drivers.$id.edit'
import { Route as CustomersIdEditRouteImport } from './routes/customers.$id.edit'
import { Route as ContractsIdEditRouteImport } from './routes/contracts.$id.edit'
import { Route as ContractRatesIdEditRouteImport } from './routes/contract-rates.$id.edit'
import { Route as BookingsIdEditRouteImport } from './routes/bookings.$id.edit'
import { Route as AgentsIdEditRouteImport } from './routes/agents.$id.edit'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleTypesRoute = VehicleTypesRouteImport.update({
  id: '/vehicle-types',
  path: '/vehicle-types',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteOverheadProfilesRoute = RouteOverheadProfilesRouteImport.update({
  id: '/route-overhead-profiles',
  path: '/route-overhead-profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteFuelProfilesRoute = RouteFuelProfilesRouteImport.update({
  id: '/route-fuel-profiles',
  path: '/route-fuel-profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelPricesRoute = FuelPricesRouteImport.update({
  id: '/fuel-prices',
  path: '/fuel-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractRatesRoute = ContractRatesRouteImport.update({
  id: '/contract-rates',
  path: '/contract-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesNewRoute = VehiclesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => VehiclesRoute,
} as any)
const VehiclesIdRoute = VehiclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VehiclesRoute,
} as any)
const VehicleTypesNewRoute = VehicleTypesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => VehicleTypesRoute,
} as any)
const VehicleTypesIdRoute = VehicleTypesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VehicleTypesRoute,
} as any)
const TripsNewRoute = TripsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TripsRoute,
} as any)
const TripsIdRoute = TripsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TripsRoute,
} as any)
const RoutesNewRoute = RoutesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RoutesRoute,
} as any)
const RoutesIdRoute = RoutesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RoutesRoute,
} as any)
const RouteOverheadProfilesNewRoute =
  RouteOverheadProfilesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => RouteOverheadProfilesRoute,
  } as any)
const RouteOverheadProfilesIdRoute = RouteOverheadProfilesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RouteOverheadProfilesRoute,
} as any)
const RouteFuelProfilesNewRoute = RouteFuelProfilesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RouteFuelProfilesRoute,
} as any)
const RouteFuelProfilesIdRoute = RouteFuelProfilesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RouteFuelProfilesRoute,
} as any)
const PricingRouteEstimateRoute = PricingRouteEstimateRouteImport.update({
  id: '/pricing/route-estimate',
  path: '/pricing/route-estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelPricesNewRoute = FuelPricesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FuelPricesRoute,
} as any)
const FuelPricesIdRoute = FuelPricesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FuelPricesRoute,
} as any)
const DriversNewRoute = DriversNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DriversRoute,
} as any)
const DriversIdRoute = DriversIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DriversRoute,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const ContractsNewRoute = ContractsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ContractsRoute,
} as any)
const ContractsIdRoute = ContractsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContractsRoute,
} as any)
const ContractRatesNewRoute = ContractRatesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ContractRatesRoute,
} as any)
const ContractRatesIdRoute = ContractRatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContractRatesRoute,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BookingsRoute,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BookingsRoute,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const VehiclesIdEditRoute = VehiclesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => VehiclesIdRoute,
} as any)
const VehicleTypesIdEditRoute = VehicleTypesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => VehicleTypesIdRoute,
} as any)
const TripsIdEditRoute = TripsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TripsIdRoute,
} as any)
const RoutesIdEditRoute = RoutesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RoutesIdRoute,
} as any)
const RouteOverheadProfilesIdEditRoute =
  RouteOverheadProfilesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => RouteOverheadProfilesIdRoute,
  } as any)
const RouteFuelProfilesIdEditRoute = RouteFuelProfilesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RouteFuelProfilesIdRoute,
} as any)
const FuelPricesIdEditRoute = FuelPricesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => FuelPricesIdRoute,
} as any)
const DriversIdEditRoute = DriversIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DriversIdRoute,
} as any)
const CustomersIdEditRoute = CustomersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CustomersIdRoute,
} as any)
const ContractsIdEditRoute = ContractsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ContractsIdRoute,
} as any)
const ContractRatesIdEditRoute = ContractRatesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ContractRatesIdRoute,
} as any)
const BookingsIdEditRoute = BookingsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BookingsIdRoute,
} as any)
const AgentsIdEditRoute = AgentsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AgentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/bookings': typeof BookingsRouteWithChildren
  '/contract-rates': typeof ContractRatesRouteWithChildren
  '/contracts': typeof ContractsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/drivers': typeof DriversRouteWithChildren
  '/fuel-prices': typeof FuelPricesRouteWithChildren
  '/route-fuel-profiles': typeof RouteFuelProfilesRouteWithChildren
  '/route-overhead-profiles': typeof RouteOverheadProfilesRouteWithChildren
  '/routes': typeof RoutesRouteWithChildren
  '/trips': typeof TripsRouteWithChildren
  '/vehicle-types': typeof VehicleTypesRouteWithChildren
  '/vehicles': typeof VehiclesRouteWithChildren
  '/agents/$id': typeof AgentsIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/bookings/$id': typeof BookingsIdRouteWithChildren
  '/bookings/new': typeof BookingsNewRoute
  '/contract-rates/$id': typeof ContractRatesIdRouteWithChildren
  '/contract-rates/new': typeof ContractRatesNewRoute
  '/contracts/$id': typeof ContractsIdRouteWithChildren
  '/contracts/new': typeof ContractsNewRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/drivers/$id': typeof DriversIdRouteWithChildren
  '/drivers/new': typeof DriversNewRoute
  '/fuel-prices/$id': typeof FuelPricesIdRouteWithChildren
  '/fuel-prices/new': typeof FuelPricesNewRoute
  '/pricing/route-estimate': typeof PricingRouteEstimateRoute
  '/route-fuel-profiles/$id': typeof RouteFuelProfilesIdRouteWithChildren
  '/route-fuel-profiles/new': typeof RouteFuelProfilesNewRoute
  '/route-overhead-profiles/$id': typeof RouteOverheadProfilesIdRouteWithChildren
  '/route-overhead-profiles/new': typeof RouteOverheadProfilesNewRoute
  '/routes/$id': typeof RoutesIdRouteWithChildren
  '/routes/new': typeof RoutesNewRoute
  '/trips/$id': typeof TripsIdRouteWithChildren
  '/trips/new': typeof TripsNewRoute
  '/vehicle-types/$id': typeof VehicleTypesIdRouteWithChildren
  '/vehicle-types/new': typeof VehicleTypesNewRoute
  '/vehicles/$id': typeof VehiclesIdRouteWithChildren
  '/vehicles/new': typeof VehiclesNewRoute
  '/agents/$id/edit': typeof AgentsIdEditRoute
  '/bookings/$id/edit': typeof BookingsIdEditRoute
  '/contract-rates/$id/edit': typeof ContractRatesIdEditRoute
  '/contracts/$id/edit': typeof ContractsIdEditRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/drivers/$id/edit': typeof DriversIdEditRoute
  '/fuel-prices/$id/edit': typeof FuelPricesIdEditRoute
  '/route-fuel-profiles/$id/edit': typeof RouteFuelProfilesIdEditRoute
  '/route-overhead-profiles/$id/edit': typeof RouteOverheadProfilesIdEditRoute
  '/routes/$id/edit': typeof RoutesIdEditRoute
  '/trips/$id/edit': typeof TripsIdEditRoute
  '/vehicle-types/$id/edit': typeof VehicleTypesIdEditRoute
  '/vehicles/$id/edit': typeof VehiclesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/bookings': typeof BookingsRouteWithChildren
  '/contract-rates': typeof ContractRatesRouteWithChildren
  '/contracts': typeof ContractsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/drivers': typeof DriversRouteWithChildren
  '/fuel-prices': typeof FuelPricesRouteWithChildren
  '/route-fuel-profiles': typeof RouteFuelProfilesRouteWithChildren
  '/route-overhead-profiles': typeof RouteOverheadProfilesRouteWithChildren
  '/routes': typeof RoutesRouteWithChildren
  '/trips': typeof TripsRouteWithChildren
  '/vehicle-types': typeof VehicleTypesRouteWithChildren
  '/vehicles': typeof VehiclesRouteWithChildren
  '/agents/$id': typeof AgentsIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/bookings/$id': typeof BookingsIdRouteWithChildren
  '/bookings/new': typeof BookingsNewRoute
  '/contract-rates/$id': typeof ContractRatesIdRouteWithChildren
  '/contract-rates/new': typeof ContractRatesNewRoute
  '/contracts/$id': typeof ContractsIdRouteWithChildren
  '/contracts/new': typeof ContractsNewRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/drivers/$id': typeof DriversIdRouteWithChildren
  '/drivers/new': typeof DriversNewRoute
  '/fuel-prices/$id': typeof FuelPricesIdRouteWithChildren
  '/fuel-prices/new': typeof FuelPricesNewRoute
  '/pricing/route-estimate': typeof PricingRouteEstimateRoute
  '/route-fuel-profiles/$id': typeof RouteFuelProfilesIdRouteWithChildren
  '/route-fuel-profiles/new': typeof RouteFuelProfilesNewRoute
  '/route-overhead-profiles/$id': typeof RouteOverheadProfilesIdRouteWithChildren
  '/route-overhead-profiles/new': typeof RouteOverheadProfilesNewRoute
  '/routes/$id': typeof RoutesIdRouteWithChildren
  '/routes/new': typeof RoutesNewRoute
  '/trips/$id': typeof TripsIdRouteWithChildren
  '/trips/new': typeof TripsNewRoute
  '/vehicle-types/$id': typeof VehicleTypesIdRouteWithChildren
  '/vehicle-types/new': typeof VehicleTypesNewRoute
  '/vehicles/$id': typeof VehiclesIdRouteWithChildren
  '/vehicles/new': typeof VehiclesNewRoute
  '/agents/$id/edit': typeof AgentsIdEditRoute
  '/bookings/$id/edit': typeof BookingsIdEditRoute
  '/contract-rates/$id/edit': typeof ContractRatesIdEditRoute
  '/contracts/$id/edit': typeof ContractsIdEditRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/drivers/$id/edit': typeof DriversIdEditRoute
  '/fuel-prices/$id/edit': typeof FuelPricesIdEditRoute
  '/route-fuel-profiles/$id/edit': typeof RouteFuelProfilesIdEditRoute
  '/route-overhead-profiles/$id/edit': typeof RouteOverheadProfilesIdEditRoute
  '/routes/$id/edit': typeof RoutesIdEditRoute
  '/trips/$id/edit': typeof TripsIdEditRoute
  '/vehicle-types/$id/edit': typeof VehicleTypesIdEditRoute
  '/vehicles/$id/edit': typeof VehiclesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/bookings': typeof BookingsRouteWithChildren
  '/contract-rates': typeof ContractRatesRouteWithChildren
  '/contracts': typeof ContractsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/drivers': typeof DriversRouteWithChildren
  '/fuel-prices': typeof FuelPricesRouteWithChildren
  '/route-fuel-profiles': typeof RouteFuelProfilesRouteWithChildren
  '/route-overhead-profiles': typeof RouteOverheadProfilesRouteWithChildren
  '/routes': typeof RoutesRouteWithChildren
  '/trips': typeof TripsRouteWithChildren
  '/vehicle-types': typeof VehicleTypesRouteWithChildren
  '/vehicles': typeof VehiclesRouteWithChildren
  '/agents/$id': typeof AgentsIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/bookings/$id': typeof BookingsIdRouteWithChildren
  '/bookings/new': typeof BookingsNewRoute
  '/contract-rates/$id': typeof ContractRatesIdRouteWithChildren
  '/contract-rates/new': typeof ContractRatesNewRoute
  '/contracts/$id': typeof ContractsIdRouteWithChildren
  '/contracts/new': typeof ContractsNewRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/drivers/$id': typeof DriversIdRouteWithChildren
  '/drivers/new': typeof DriversNewRoute
  '/fuel-prices/$id': typeof FuelPricesIdRouteWithChildren
  '/fuel-prices/new': typeof FuelPricesNewRoute
  '/pricing/route-estimate': typeof PricingRouteEstimateRoute
  '/route-fuel-profiles/$id': typeof RouteFuelProfilesIdRouteWithChildren
  '/route-fuel-profiles/new': typeof RouteFuelProfilesNewRoute
  '/route-overhead-profiles/$id': typeof RouteOverheadProfilesIdRouteWithChildren
  '/route-overhead-profiles/new': typeof RouteOverheadProfilesNewRoute
  '/routes/$id': typeof RoutesIdRouteWithChildren
  '/routes/new': typeof RoutesNewRoute
  '/trips/$id': typeof TripsIdRouteWithChildren
  '/trips/new': typeof TripsNewRoute
  '/vehicle-types/$id': typeof VehicleTypesIdRouteWithChildren
  '/vehicle-types/new': typeof VehicleTypesNewRoute
  '/vehicles/$id': typeof VehiclesIdRouteWithChildren
  '/vehicles/new': typeof VehiclesNewRoute
  '/agents/$id/edit': typeof AgentsIdEditRoute
  '/bookings/$id/edit': typeof BookingsIdEditRoute
  '/contract-rates/$id/edit': typeof ContractRatesIdEditRoute
  '/contracts/$id/edit': typeof ContractsIdEditRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/drivers/$id/edit': typeof DriversIdEditRoute
  '/fuel-prices/$id/edit': typeof FuelPricesIdEditRoute
  '/route-fuel-profiles/$id/edit': typeof RouteFuelProfilesIdEditRoute
  '/route-overhead-profiles/$id/edit': typeof RouteOverheadProfilesIdEditRoute
  '/routes/$id/edit': typeof RoutesIdEditRoute
  '/trips/$id/edit': typeof TripsIdEditRoute
  '/vehicle-types/$id/edit': typeof VehicleTypesIdEditRoute
  '/vehicles/$id/edit': typeof VehiclesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/bookings'
    | '/contract-rates'
    | '/contracts'
    | '/customers'
    | '/drivers'
    | '/fuel-prices'
    | '/route-fuel-profiles'
    | '/route-overhead-profiles'
    | '/routes'
    | '/trips'
    | '/vehicle-types'
    | '/vehicles'
    | '/agents/$id'
    | '/agents/new'
    | '/bookings/$id'
    | '/bookings/new'
    | '/contract-rates/$id'
    | '/contract-rates/new'
    | '/contracts/$id'
    | '/contracts/new'
    | '/customers/$id'
    | '/customers/new'
    | '/drivers/$id'
    | '/drivers/new'
    | '/fuel-prices/$id'
    | '/fuel-prices/new'
    | '/pricing/route-estimate'
    | '/route-fuel-profiles/$id'
    | '/route-fuel-profiles/new'
    | '/route-overhead-profiles/$id'
    | '/route-overhead-profiles/new'
    | '/routes/$id'
    | '/routes/new'
    | '/trips/$id'
    | '/trips/new'
    | '/vehicle-types/$id'
    | '/vehicle-types/new'
    | '/vehicles/$id'
    | '/vehicles/new'
    | '/agents/$id/edit'
    | '/bookings/$id/edit'
    | '/contract-rates/$id/edit'
    | '/contracts/$id/edit'
    | '/customers/$id/edit'
    | '/drivers/$id/edit'
    | '/fuel-prices/$id/edit'
    | '/route-fuel-profiles/$id/edit'
    | '/route-overhead-profiles/$id/edit'
    | '/routes/$id/edit'
    | '/trips/$id/edit'
    | '/vehicle-types/$id/edit'
    | '/vehicles/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/bookings'
    | '/contract-rates'
    | '/contracts'
    | '/customers'
    | '/drivers'
    | '/fuel-prices'
    | '/route-fuel-profiles'
    | '/route-overhead-profiles'
    | '/routes'
    | '/trips'
    | '/vehicle-types'
    | '/vehicles'
    | '/agents/$id'
    | '/agents/new'
    | '/bookings/$id'
    | '/bookings/new'
    | '/contract-rates/$id'
    | '/contract-rates/new'
    | '/contracts/$id'
    | '/contracts/new'
    | '/customers/$id'
    | '/customers/new'
    | '/drivers/$id'
    | '/drivers/new'
    | '/fuel-prices/$id'
    | '/fuel-prices/new'
    | '/pricing/route-estimate'
    | '/route-fuel-profiles/$id'
    | '/route-fuel-profiles/new'
    | '/route-overhead-profiles/$id'
    | '/route-overhead-profiles/new'
    | '/routes/$id'
    | '/routes/new'
    | '/trips/$id'
    | '/trips/new'
    | '/vehicle-types/$id'
    | '/vehicle-types/new'
    | '/vehicles/$id'
    | '/vehicles/new'
    | '/agents/$id/edit'
    | '/bookings/$id/edit'
    | '/contract-rates/$id/edit'
    | '/contracts/$id/edit'
    | '/customers/$id/edit'
    | '/drivers/$id/edit'
    | '/fuel-prices/$id/edit'
    | '/route-fuel-profiles/$id/edit'
    | '/route-overhead-profiles/$id/edit'
    | '/routes/$id/edit'
    | '/trips/$id/edit'
    | '/vehicle-types/$id/edit'
    | '/vehicles/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/bookings'
    | '/contract-rates'
    | '/contracts'
    | '/customers'
    | '/drivers'
    | '/fuel-prices'
    | '/route-fuel-profiles'
    | '/route-overhead-profiles'
    | '/routes'
    | '/trips'
    | '/vehicle-types'
    | '/vehicles'
    | '/agents/$id'
    | '/agents/new'
    | '/bookings/$id'
    | '/bookings/new'
    | '/contract-rates/$id'
    | '/contract-rates/new'
    | '/contracts/$id'
    | '/contracts/new'
    | '/customers/$id'
    | '/customers/new'
    | '/drivers/$id'
    | '/drivers/new'
    | '/fuel-prices/$id'
    | '/fuel-prices/new'
    | '/pricing/route-estimate'
    | '/route-fuel-profiles/$id'
    | '/route-fuel-profiles/new'
    | '/route-overhead-profiles/$id'
    | '/route-overhead-profiles/new'
    | '/routes/$id'
    | '/routes/new'
    | '/trips/$id'
    | '/trips/new'
    | '/vehicle-types/$id'
    | '/vehicle-types/new'
    | '/vehicles/$id'
    | '/vehicles/new'
    | '/agents/$id/edit'
    | '/bookings/$id/edit'
    | '/contract-rates/$id/edit'
    | '/contracts/$id/edit'
    | '/customers/$id/edit'
    | '/drivers/$id/edit'
    | '/fuel-prices/$id/edit'
    | '/route-fuel-profiles/$id/edit'
    | '/route-overhead-profiles/$id/edit'
    | '/routes/$id/edit'
    | '/trips/$id/edit'
    | '/vehicle-types/$id/edit'
    | '/vehicles/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  BookingsRoute: typeof BookingsRouteWithChildren
  ContractRatesRoute: typeof ContractRatesRouteWithChildren
  ContractsRoute: typeof ContractsRouteWithChildren
  CustomersRoute: typeof CustomersRouteWithChildren
  DriversRoute: typeof DriversRouteWithChildren
  FuelPricesRoute: typeof FuelPricesRouteWithChildren
  RouteFuelProfilesRoute: typeof RouteFuelProfilesRouteWithChildren
  RouteOverheadProfilesRoute: typeof RouteOverheadProfilesRouteWithChildren
  RoutesRoute: typeof RoutesRouteWithChildren
  TripsRoute: typeof TripsRouteWithChildren
  VehicleTypesRoute: typeof VehicleTypesRouteWithChildren
  VehiclesRoute: typeof VehiclesRouteWithChildren
  PricingRouteEstimateRoute: typeof PricingRouteEstimateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-types': {
      id: '/vehicle-types'
      path: '/vehicle-types'
      fullPath: '/vehicle-types'
      preLoaderRoute: typeof VehicleTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-overhead-profiles': {
      id: '/route-overhead-profiles'
      path: '/route-overhead-profiles'
      fullPath: '/route-overhead-profiles'
      preLoaderRoute: typeof RouteOverheadProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-fuel-profiles': {
      id: '/route-fuel-profiles'
      path: '/route-fuel-profiles'
      fullPath: '/route-fuel-profiles'
      preLoaderRoute: typeof RouteFuelProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel-prices': {
      id: '/fuel-prices'
      path: '/fuel-prices'
      fullPath: '/fuel-prices'
      preLoaderRoute: typeof FuelPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract-rates': {
      id: '/contract-rates'
      path: '/contract-rates'
      fullPath: '/contract-rates'
      preLoaderRoute: typeof ContractRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/new': {
      id: '/vehicles/new'
      path: '/new'
      fullPath: '/vehicles/new'
      preLoaderRoute: typeof VehiclesNewRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/vehicles/$id': {
      id: '/vehicles/$id'
      path: '/$id'
      fullPath: '/vehicles/$id'
      preLoaderRoute: typeof VehiclesIdRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/vehicle-types/new': {
      id: '/vehicle-types/new'
      path: '/new'
      fullPath: '/vehicle-types/new'
      preLoaderRoute: typeof VehicleTypesNewRouteImport
      parentRoute: typeof VehicleTypesRoute
    }
    '/vehicle-types/$id': {
      id: '/vehicle-types/$id'
      path: '/$id'
      fullPath: '/vehicle-types/$id'
      preLoaderRoute: typeof VehicleTypesIdRouteImport
      parentRoute: typeof VehicleTypesRoute
    }
    '/trips/new': {
      id: '/trips/new'
      path: '/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof TripsNewRouteImport
      parentRoute: typeof TripsRoute
    }
    '/trips/$id': {
      id: '/trips/$id'
      path: '/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof TripsIdRouteImport
      parentRoute: typeof TripsRoute
    }
    '/routes/new': {
      id: '/routes/new'
      path: '/new'
      fullPath: '/routes/new'
      preLoaderRoute: typeof RoutesNewRouteImport
      parentRoute: typeof RoutesRoute
    }
    '/routes/$id': {
      id: '/routes/$id'
      path: '/$id'
      fullPath: '/routes/$id'
      preLoaderRoute: typeof RoutesIdRouteImport
      parentRoute: typeof RoutesRoute
    }
    '/route-overhead-profiles/new': {
      id: '/route-overhead-profiles/new'
      path: '/new'
      fullPath: '/route-overhead-profiles/new'
      preLoaderRoute: typeof RouteOverheadProfilesNewRouteImport
      parentRoute: typeof RouteOverheadProfilesRoute
    }
    '/route-overhead-profiles/$id': {
      id: '/route-overhead-profiles/$id'
      path: '/$id'
      fullPath: '/route-overhead-profiles/$id'
      preLoaderRoute: typeof RouteOverheadProfilesIdRouteImport
      parentRoute: typeof RouteOverheadProfilesRoute
    }
    '/route-fuel-profiles/new': {
      id: '/route-fuel-profiles/new'
      path: '/new'
      fullPath: '/route-fuel-profiles/new'
      preLoaderRoute: typeof RouteFuelProfilesNewRouteImport
      parentRoute: typeof RouteFuelProfilesRoute
    }
    '/route-fuel-profiles/$id': {
      id: '/route-fuel-profiles/$id'
      path: '/$id'
      fullPath: '/route-fuel-profiles/$id'
      preLoaderRoute: typeof RouteFuelProfilesIdRouteImport
      parentRoute: typeof RouteFuelProfilesRoute
    }
    '/pricing/route-estimate': {
      id: '/pricing/route-estimate'
      path: '/pricing/route-estimate'
      fullPath: '/pricing/route-estimate'
      preLoaderRoute: typeof PricingRouteEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel-prices/new': {
      id: '/fuel-prices/new'
      path: '/new'
      fullPath: '/fuel-prices/new'
      preLoaderRoute: typeof FuelPricesNewRouteImport
      parentRoute: typeof FuelPricesRoute
    }
    '/fuel-prices/$id': {
      id: '/fuel-prices/$id'
      path: '/$id'
      fullPath: '/fuel-prices/$id'
      preLoaderRoute: typeof FuelPricesIdRouteImport
      parentRoute: typeof FuelPricesRoute
    }
    '/drivers/new': {
      id: '/drivers/new'
      path: '/new'
      fullPath: '/drivers/new'
      preLoaderRoute: typeof DriversNewRouteImport
      parentRoute: typeof DriversRoute
    }
    '/drivers/$id': {
      id: '/drivers/$id'
      path: '/$id'
      fullPath: '/drivers/$id'
      preLoaderRoute: typeof DriversIdRouteImport
      parentRoute: typeof DriversRoute
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/contracts/new': {
      id: '/contracts/new'
      path: '/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof ContractsNewRouteImport
      parentRoute: typeof ContractsRoute
    }
    '/contracts/$id': {
      id: '/contracts/$id'
      path: '/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof ContractsIdRouteImport
      parentRoute: typeof ContractsRoute
    }
    '/contract-rates/new': {
      id: '/contract-rates/new'
      path: '/new'
      fullPath: '/contract-rates/new'
      preLoaderRoute: typeof ContractRatesNewRouteImport
      parentRoute: typeof ContractRatesRoute
    }
    '/contract-rates/$id': {
      id: '/contract-rates/$id'
      path: '/$id'
      fullPath: '/contract-rates/$id'
      preLoaderRoute: typeof ContractRatesIdRouteImport
      parentRoute: typeof ContractRatesRoute
    }
    '/bookings/new': {
      id: '/bookings/new'
      path: '/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/vehicles/$id/edit': {
      id: '/vehicles/$id/edit'
      path: '/edit'
      fullPath: '/vehicles/$id/edit'
      preLoaderRoute: typeof VehiclesIdEditRouteImport
      parentRoute: typeof VehiclesIdRoute
    }
    '/vehicle-types/$id/edit': {
      id: '/vehicle-types/$id/edit'
      path: '/edit'
      fullPath: '/vehicle-types/$id/edit'
      preLoaderRoute: typeof VehicleTypesIdEditRouteImport
      parentRoute: typeof VehicleTypesIdRoute
    }
    '/trips/$id/edit': {
      id: '/trips/$id/edit'
      path: '/edit'
      fullPath: '/trips/$id/edit'
      preLoaderRoute: typeof TripsIdEditRouteImport
      parentRoute: typeof TripsIdRoute
    }
    '/routes/$id/edit': {
      id: '/routes/$id/edit'
      path: '/edit'
      fullPath: '/routes/$id/edit'
      preLoaderRoute: typeof RoutesIdEditRouteImport
      parentRoute: typeof RoutesIdRoute
    }
    '/route-overhead-profiles/$id/edit': {
      id: '/route-overhead-profiles/$id/edit'
      path: '/edit'
      fullPath: '/route-overhead-profiles/$id/edit'
      preLoaderRoute: typeof RouteOverheadProfilesIdEditRouteImport
      parentRoute: typeof RouteOverheadProfilesIdRoute
    }
    '/route-fuel-profiles/$id/edit': {
      id: '/route-fuel-profiles/$id/edit'
      path: '/edit'
      fullPath: '/route-fuel-profiles/$id/edit'
      preLoaderRoute: typeof RouteFuelProfilesIdEditRouteImport
      parentRoute: typeof RouteFuelProfilesIdRoute
    }
    '/fuel-prices/$id/edit': {
      id: '/fuel-prices/$id/edit'
      path: '/edit'
      fullPath: '/fuel-prices/$id/edit'
      preLoaderRoute: typeof FuelPricesIdEditRouteImport
      parentRoute: typeof FuelPricesIdRoute
    }
    '/drivers/$id/edit': {
      id: '/drivers/$id/edit'
      path: '/edit'
      fullPath: '/drivers/$id/edit'
      preLoaderRoute: typeof DriversIdEditRouteImport
      parentRoute: typeof DriversIdRoute
    }
    '/customers/$id/edit': {
      id: '/customers/$id/edit'
      path: '/edit'
      fullPath: '/customers/$id/edit'
      preLoaderRoute: typeof CustomersIdEditRouteImport
      parentRoute: typeof CustomersIdRoute
    }
    '/contracts/$id/edit': {
      id: '/contracts/$id/edit'
      path: '/edit'
      fullPath: '/contracts/$id/edit'
      preLoaderRoute: typeof ContractsIdEditRouteImport
      parentRoute: typeof ContractsIdRoute
    }
    '/contract-rates/$id/edit': {
      id: '/contract-rates/$id/edit'
      path: '/edit'
      fullPath: '/contract-rates/$id/edit'
      preLoaderRoute: typeof ContractRatesIdEditRouteImport
      parentRoute: typeof ContractRatesIdRoute
    }
    '/bookings/$id/edit': {
      id: '/bookings/$id/edit'
      path: '/edit'
      fullPath: '/bookings/$id/edit'
      preLoaderRoute: typeof BookingsIdEditRouteImport
      parentRoute: typeof BookingsIdRoute
    }
    '/agents/$id/edit': {
      id: '/agents/$id/edit'
      path: '/edit'
      fullPath: '/agents/$id/edit'
      preLoaderRoute: typeof AgentsIdEditRouteImport
      parentRoute: typeof AgentsIdRoute
    }
  }
}

interface AgentsIdRouteChildren {
  AgentsIdEditRoute: typeof AgentsIdEditRoute
}

const AgentsIdRouteChildren: AgentsIdRouteChildren = {
  AgentsIdEditRoute: AgentsIdEditRoute,
}

const AgentsIdRouteWithChildren = AgentsIdRoute._addFileChildren(
  AgentsIdRouteChildren,
)

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRouteWithChildren
  AgentsNewRoute: typeof AgentsNewRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRouteWithChildren,
  AgentsNewRoute: AgentsNewRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface BookingsIdRouteChildren {
  BookingsIdEditRoute: typeof BookingsIdEditRoute
}

const BookingsIdRouteChildren: BookingsIdRouteChildren = {
  BookingsIdEditRoute: BookingsIdEditRoute,
}

const BookingsIdRouteWithChildren = BookingsIdRoute._addFileChildren(
  BookingsIdRouteChildren,
)

interface BookingsRouteChildren {
  BookingsIdRoute: typeof BookingsIdRouteWithChildren
  BookingsNewRoute: typeof BookingsNewRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsIdRoute: BookingsIdRouteWithChildren,
  BookingsNewRoute: BookingsNewRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

interface ContractRatesIdRouteChildren {
  ContractRatesIdEditRoute: typeof ContractRatesIdEditRoute
}

const ContractRatesIdRouteChildren: ContractRatesIdRouteChildren = {
  ContractRatesIdEditRoute: ContractRatesIdEditRoute,
}

const ContractRatesIdRouteWithChildren = ContractRatesIdRoute._addFileChildren(
  ContractRatesIdRouteChildren,
)

interface ContractRatesRouteChildren {
  ContractRatesIdRoute: typeof ContractRatesIdRouteWithChildren
  ContractRatesNewRoute: typeof ContractRatesNewRoute
}

const ContractRatesRouteChildren: ContractRatesRouteChildren = {
  ContractRatesIdRoute: ContractRatesIdRouteWithChildren,
  ContractRatesNewRoute: ContractRatesNewRoute,
}

const ContractRatesRouteWithChildren = ContractRatesRoute._addFileChildren(
  ContractRatesRouteChildren,
)

interface ContractsIdRouteChildren {
  ContractsIdEditRoute: typeof ContractsIdEditRoute
}

const ContractsIdRouteChildren: ContractsIdRouteChildren = {
  ContractsIdEditRoute: ContractsIdEditRoute,
}

const ContractsIdRouteWithChildren = ContractsIdRoute._addFileChildren(
  ContractsIdRouteChildren,
)

interface ContractsRouteChildren {
  ContractsIdRoute: typeof ContractsIdRouteWithChildren
  ContractsNewRoute: typeof ContractsNewRoute
}

const ContractsRouteChildren: ContractsRouteChildren = {
  ContractsIdRoute: ContractsIdRouteWithChildren,
  ContractsNewRoute: ContractsNewRoute,
}

const ContractsRouteWithChildren = ContractsRoute._addFileChildren(
  ContractsRouteChildren,
)

interface CustomersIdRouteChildren {
  CustomersIdEditRoute: typeof CustomersIdEditRoute
}

const CustomersIdRouteChildren: CustomersIdRouteChildren = {
  CustomersIdEditRoute: CustomersIdEditRoute,
}

const CustomersIdRouteWithChildren = CustomersIdRoute._addFileChildren(
  CustomersIdRouteChildren,
)

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRouteWithChildren
  CustomersNewRoute: typeof CustomersNewRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRouteWithChildren,
  CustomersNewRoute: CustomersNewRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface DriversIdRouteChildren {
  DriversIdEditRoute: typeof DriversIdEditRoute
}

const DriversIdRouteChildren: DriversIdRouteChildren = {
  DriversIdEditRoute: DriversIdEditRoute,
}

const DriversIdRouteWithChildren = DriversIdRoute._addFileChildren(
  DriversIdRouteChildren,
)

interface DriversRouteChildren {
  DriversIdRoute: typeof DriversIdRouteWithChildren
  DriversNewRoute: typeof DriversNewRoute
}

const DriversRouteChildren: DriversRouteChildren = {
  DriversIdRoute: DriversIdRouteWithChildren,
  DriversNewRoute: DriversNewRoute,
}

const DriversRouteWithChildren =
  DriversRoute._addFileChildren(DriversRouteChildren)

interface FuelPricesIdRouteChildren {
  FuelPricesIdEditRoute: typeof FuelPricesIdEditRoute
}

const FuelPricesIdRouteChildren: FuelPricesIdRouteChildren = {
  FuelPricesIdEditRoute: FuelPricesIdEditRoute,
}

const FuelPricesIdRouteWithChildren = FuelPricesIdRoute._addFileChildren(
  FuelPricesIdRouteChildren,
)

interface FuelPricesRouteChildren {
  FuelPricesIdRoute: typeof FuelPricesIdRouteWithChildren
  FuelPricesNewRoute: typeof FuelPricesNewRoute
}

const FuelPricesRouteChildren: FuelPricesRouteChildren = {
  FuelPricesIdRoute: FuelPricesIdRouteWithChildren,
  FuelPricesNewRoute: FuelPricesNewRoute,
}

const FuelPricesRouteWithChildren = FuelPricesRoute._addFileChildren(
  FuelPricesRouteChildren,
)

interface RouteFuelProfilesIdRouteChildren {
  RouteFuelProfilesIdEditRoute: typeof RouteFuelProfilesIdEditRoute
}

const RouteFuelProfilesIdRouteChildren: RouteFuelProfilesIdRouteChildren = {
  RouteFuelProfilesIdEditRoute: RouteFuelProfilesIdEditRoute,
}

const RouteFuelProfilesIdRouteWithChildren =
  RouteFuelProfilesIdRoute._addFileChildren(RouteFuelProfilesIdRouteChildren)

interface RouteFuelProfilesRouteChildren {
  RouteFuelProfilesIdRoute: typeof RouteFuelProfilesIdRouteWithChildren
  RouteFuelProfilesNewRoute: typeof RouteFuelProfilesNewRoute
}

const RouteFuelProfilesRouteChildren: RouteFuelProfilesRouteChildren = {
  RouteFuelProfilesIdRoute: RouteFuelProfilesIdRouteWithChildren,
  RouteFuelProfilesNewRoute: RouteFuelProfilesNewRoute,
}

const RouteFuelProfilesRouteWithChildren =
  RouteFuelProfilesRoute._addFileChildren(RouteFuelProfilesRouteChildren)

interface RouteOverheadProfilesIdRouteChildren {
  RouteOverheadProfilesIdEditRoute: typeof RouteOverheadProfilesIdEditRoute
}

const RouteOverheadProfilesIdRouteChildren: RouteOverheadProfilesIdRouteChildren =
  {
    RouteOverheadProfilesIdEditRoute: RouteOverheadProfilesIdEditRoute,
  }

const RouteOverheadProfilesIdRouteWithChildren =
  RouteOverheadProfilesIdRoute._addFileChildren(
    RouteOverheadProfilesIdRouteChildren,
  )

interface RouteOverheadProfilesRouteChildren {
  RouteOverheadProfilesIdRoute: typeof RouteOverheadProfilesIdRouteWithChildren
  RouteOverheadProfilesNewRoute: typeof RouteOverheadProfilesNewRoute
}

const RouteOverheadProfilesRouteChildren: RouteOverheadProfilesRouteChildren = {
  RouteOverheadProfilesIdRoute: RouteOverheadProfilesIdRouteWithChildren,
  RouteOverheadProfilesNewRoute: RouteOverheadProfilesNewRoute,
}

const RouteOverheadProfilesRouteWithChildren =
  RouteOverheadProfilesRoute._addFileChildren(
    RouteOverheadProfilesRouteChildren,
  )

interface RoutesIdRouteChildren {
  RoutesIdEditRoute: typeof RoutesIdEditRoute
}

const RoutesIdRouteChildren: RoutesIdRouteChildren = {
  RoutesIdEditRoute: RoutesIdEditRoute,
}

const RoutesIdRouteWithChildren = RoutesIdRoute._addFileChildren(
  RoutesIdRouteChildren,
)

interface RoutesRouteChildren {
  RoutesIdRoute: typeof RoutesIdRouteWithChildren
  RoutesNewRoute: typeof RoutesNewRoute
}

const RoutesRouteChildren: RoutesRouteChildren = {
  RoutesIdRoute: RoutesIdRouteWithChildren,
  RoutesNewRoute: RoutesNewRoute,
}

const RoutesRouteWithChildren =
  RoutesRoute._addFileChildren(RoutesRouteChildren)

interface TripsIdRouteChildren {
  TripsIdEditRoute: typeof TripsIdEditRoute
}

const TripsIdRouteChildren: TripsIdRouteChildren = {
  TripsIdEditRoute: TripsIdEditRoute,
}

const TripsIdRouteWithChildren =
  TripsIdRoute._addFileChildren(TripsIdRouteChildren)

interface TripsRouteChildren {
  TripsIdRoute: typeof TripsIdRouteWithChildren
  TripsNewRoute: typeof TripsNewRoute
}

const TripsRouteChildren: TripsRouteChildren = {
  TripsIdRoute: TripsIdRouteWithChildren,
  TripsNewRoute: TripsNewRoute,
}

const TripsRouteWithChildren = TripsRoute._addFileChildren(TripsRouteChildren)

interface VehicleTypesIdRouteChildren {
  VehicleTypesIdEditRoute: typeof VehicleTypesIdEditRoute
}

const VehicleTypesIdRouteChildren: VehicleTypesIdRouteChildren = {
  VehicleTypesIdEditRoute: VehicleTypesIdEditRoute,
}

const VehicleTypesIdRouteWithChildren = VehicleTypesIdRoute._addFileChildren(
  VehicleTypesIdRouteChildren,
)

interface VehicleTypesRouteChildren {
  VehicleTypesIdRoute: typeof VehicleTypesIdRouteWithChildren
  VehicleTypesNewRoute: typeof VehicleTypesNewRoute
}

const VehicleTypesRouteChildren: VehicleTypesRouteChildren = {
  VehicleTypesIdRoute: VehicleTypesIdRouteWithChildren,
  VehicleTypesNewRoute: VehicleTypesNewRoute,
}

const VehicleTypesRouteWithChildren = VehicleTypesRoute._addFileChildren(
  VehicleTypesRouteChildren,
)

interface VehiclesIdRouteChildren {
  VehiclesIdEditRoute: typeof VehiclesIdEditRoute
}

const VehiclesIdRouteChildren: VehiclesIdRouteChildren = {
  VehiclesIdEditRoute: VehiclesIdEditRoute,
}

const VehiclesIdRouteWithChildren = VehiclesIdRoute._addFileChildren(
  VehiclesIdRouteChildren,
)

interface VehiclesRouteChildren {
  VehiclesIdRoute: typeof VehiclesIdRouteWithChildren
  VehiclesNewRoute: typeof VehiclesNewRoute
}

const VehiclesRouteChildren: VehiclesRouteChildren = {
  VehiclesIdRoute: VehiclesIdRouteWithChildren,
  VehiclesNewRoute: VehiclesNewRoute,
}

const VehiclesRouteWithChildren = VehiclesRoute._addFileChildren(
  VehiclesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  BookingsRoute: BookingsRouteWithChildren,
  ContractRatesRoute: ContractRatesRouteWithChildren,
  ContractsRoute: ContractsRouteWithChildren,
  CustomersRoute: CustomersRouteWithChildren,
  DriversRoute: DriversRouteWithChildren,
  FuelPricesRoute: FuelPricesRouteWithChildren,
  RouteFuelProfilesRoute: RouteFuelProfilesRouteWithChildren,
  RouteOverheadProfilesRoute: RouteOverheadProfilesRouteWithChildren,
  RoutesRoute: RoutesRouteWithChildren,
  TripsRoute: TripsRouteWithChildren,
  VehicleTypesRoute: VehicleTypesRouteWithChildren,
  VehiclesRoute: VehiclesRouteWithChildren,
  PricingRouteEstimateRoute: PricingRouteEstimateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
