import { BadRequestException,ConflictException,Injectable,NotFoundException } from '@nestjs/common'; import type { CreateVehicleRequest,UpdateVehicleRequest,VehicleStatus as VehicleStatusType } from '@ems/api-contract'; import { VehicleStatus } from '@ems/shared'; import { booleanOrDefault,optionalBoolean,optionalDate,optionalPositiveInt,optionalString,pagination,positiveInt,requiredString } from '../../common/utils/master-data.utils'; import { toVehicleResponse,toVehiclesListResponse } from './vehicles.mapper'; import { VehiclesRepository } from './vehicles.repository';
@Injectable() export class VehiclesService {constructor(private readonly repo:VehiclesRepository){}
 private status(v:unknown):VehicleStatusType{if(typeof v!=='string'||!Object.values(VehicleStatus).includes(v as never))throw new BadRequestException({error:{code:'INVALID_VEHICLE_STATUS',message:'Vehicle status is invalid'}});return v as VehicleStatusType;}
 async list(q:Record<string,unknown>){const p=pagination(q.page,q.limit);const f={search:optionalString(q.search)??undefined,isActive:optionalBoolean(q.isActive,'isActive'),stationId:optionalPositiveInt(q.stationId,'stationId'),vehicleTypeId:optionalPositiveInt(q.vehicleTypeId,'vehicleTypeId'),status:q.status===undefined?undefined:this.status(q.status)};const[rows,total]=await Promise.all([this.repo.findAll(f,p.offset,p.limit),this.repo.count(f)]);return toVehiclesListResponse(rows,p.page,p.limit,total);}
 async get(v:unknown){const r=await this.repo.findById(positiveInt(v,'vehicleId'));if(!r)throw this.notFound();return toVehicleResponse(r);}
 async create(b:CreateVehicleRequest){const n=requiredString(b.vehicleNumber,'vehicleNumber').toUpperCase();if(await this.repo.findByNumber(n))throw new ConflictException({error:{code:'VEHICLE_NUMBER_EXISTS',message:'Vehicle number already exists'}});await this.refs(b.vehicleTypeId,b.currentStationId);const r=await this.repo.create({vehicleNumber:n,vehicleTypeId:positiveInt(b.vehicleTypeId,'vehicleTypeId'),currentStationId:positiveInt(b.currentStationId,'currentStationId'),status:this.status(b.status),fuelCardNumber:optionalString(b.fuelCardNumber),registrationExpiry:optionalDate(b.registrationExpiry,'registrationExpiry'),fitnessExpiry:optionalDate(b.fitnessExpiry,'fitnessExpiry'),insuranceExpiry:optionalDate(b.insuranceExpiry,'insuranceExpiry'),isActive:booleanOrDefault(b.isActive)});return toVehicleResponse(r!);}
 async update(v:unknown,b:UpdateVehicleRequest){const id=positiveInt(v,'vehicleId'),e=await this.repo.findById(id);if(!e)throw this.notFound();let n:string|undefined;if(b.vehicleNumber!==undefined){n=requiredString(b.vehicleNumber,'vehicleNumber').toUpperCase();const d=await this.repo.findByNumber(n);if(d&&d.id!==id)throw new ConflictException({error:{code:'VEHICLE_NUMBER_EXISTS',message:'Vehicle number already exists'}});}if(b.vehicleTypeId!==undefined||b.currentStationId!==undefined)await this.refs(b.vehicleTypeId??e.vehicleTypeId,b.currentStationId??e.stationId);const r=await this.repo.update(id,{vehicleNumber:n,vehicleTypeId:b.vehicleTypeId,currentStationId:b.currentStationId,status:b.status===undefined?undefined:this.status(b.status),fuelCardNumber:b.fuelCardNumber===undefined?undefined:optionalString(b.fuelCardNumber),registrationExpiry:b.registrationExpiry===undefined?undefined:optionalDate(b.registrationExpiry,'registrationExpiry'),fitnessExpiry:b.fitnessExpiry===undefined?undefined:optionalDate(b.fitnessExpiry,'fitnessExpiry'),insuranceExpiry:b.insuranceExpiry===undefined?undefined:optionalDate(b.insuranceExpiry,'insuranceExpiry'),isActive:optionalBoolean(b.isActive,'isActive')});return toVehicleResponse(r!);}
 async remove(v:unknown){const id=positiveInt(v,'vehicleId');if(!(await this.repo.findById(id)))throw this.notFound();return toVehicleResponse((await this.repo.update(id,{isActive:false,status:VehicleStatus.INACTIVE}))!);}
 private async refs(t:unknown,s:unknown){const ti=positiveInt(t,'vehicleTypeId'),si=positiveInt(s,'currentStationId');if(!(await this.repo.vehicleTypeExists(ti)))throw new BadRequestException({error:{code:'VEHICLE_TYPE_NOT_FOUND',message:'Active vehicle type not found'}});if(!(await this.repo.stationExists(si)))throw new BadRequestException({error:{code:'STATION_NOT_FOUND',message:'Active station not found'}});}
 private notFound(){return new NotFoundException({error:{code:'VEHICLE_NOT_FOUND',message:'Vehicle not found'}});}
}
