import { Inject,Injectable } from '@nestjs/common'; import type { DB as EMSDB } from '@ems/db'; import type { Kysely,Updateable } from 'kysely'; import { DB } from '../../database/database.tokens';
type Filters={search?:string;isActive?:boolean;stationId?:number;vehicleTypeId?:number;status?:string};
@Injectable() export class VehiclesRepository {constructor(@Inject(DB) private readonly db:Kysely<EMSDB>){}
 private base(){return this.db.selectFrom('vehicles').innerJoin('vehicle_types','vehicle_types.id','vehicles.vehicle_type_id').innerJoin('stations','stations.id','vehicles.current_station_id').innerJoin('cities','cities.id','stations.city_id').select(['vehicles.id as id','vehicles.vehicle_number as vehicleNumber','vehicles.status as status','vehicles.fuel_card_number as fuelCardNumber','vehicles.registration_expiry as registrationExpiry','vehicles.fitness_expiry as fitnessExpiry','vehicles.insurance_expiry as insuranceExpiry','vehicles.is_active as isActive','vehicles.created_at as createdAt','vehicles.updated_at as updatedAt','vehicle_types.id as vehicleTypeId','vehicle_types.name as vehicleTypeName','vehicle_types.code as vehicleTypeCode','vehicle_types.capacity_tons as vehicleTypeCapacityTons','vehicle_types.description as vehicleTypeDescription','vehicle_types.is_active as vehicleTypeIsActive','vehicle_types.created_at as vehicleTypeCreatedAt','vehicle_types.updated_at as vehicleTypeUpdatedAt','stations.id as stationId','stations.city_id as stationCityId','cities.name as stationCityName','stations.name as stationName','stations.code as stationCode','stations.address as stationAddress','stations.contact_phone as stationContactPhone','stations.is_active as stationIsActive','stations.created_at as stationCreatedAt']);}
 private apply<T extends ReturnType<VehiclesRepository['base']>>(q:T,f:Filters):T{let x=q;if(f.search)x=x.where('vehicles.vehicle_number','ilike',`%${f.search}%`) as T;if(f.isActive!==undefined)x=x.where('vehicles.is_active','=',f.isActive) as T;if(f.stationId)x=x.where('vehicles.current_station_id','=',f.stationId) as T;if(f.vehicleTypeId)x=x.where('vehicles.vehicle_type_id','=',f.vehicleTypeId) as T;if(f.status)x=x.where('vehicles.status','=',f.status) as T;return x;}
 findAll(f:Filters,o:number,l:number){return this.apply(this.base(),f).orderBy('vehicles.vehicle_number').offset(o).limit(l).execute();}
 async count(f:Filters){let q=this.db.selectFrom('vehicles').select((eb)=>eb.fn.countAll<number>().as('total'));if(f.search)q=q.where('vehicle_number','ilike',`%${f.search}%`);if(f.isActive!==undefined)q=q.where('is_active','=',f.isActive);if(f.stationId)q=q.where('current_station_id','=',f.stationId);if(f.vehicleTypeId)q=q.where('vehicle_type_id','=',f.vehicleTypeId);if(f.status)q=q.where('status','=',f.status);return(await q.executeTakeFirstOrThrow()).total;}
 findById(id:number){return this.base().where('vehicles.id','=',id).executeTakeFirst();} findByNumber(n:string){return this.db.selectFrom('vehicles').select('id').where('vehicle_number','=',n).executeTakeFirst();}
 vehicleTypeExists(id:number){return this.db.selectFrom('vehicle_types').select('id').where('id','=',id).where('is_active','=',true).executeTakeFirst();} stationExists(id:number){return this.db.selectFrom('stations').select('id').where('id','=',id).where('is_active','=',true).executeTakeFirst();}
 async create(i:{vehicleNumber:string;vehicleTypeId:number;currentStationId:number;status:string;fuelCardNumber:string|null;registrationExpiry:string|null;fitnessExpiry:string|null;insuranceExpiry:string|null;isActive:boolean}){const r=await this.db.insertInto('vehicles').values({vehicle_number:i.vehicleNumber,vehicle_type_id:i.vehicleTypeId,current_station_id:i.currentStationId,status:i.status,fuel_card_number:i.fuelCardNumber,registration_expiry:i.registrationExpiry,fitness_expiry:i.fitnessExpiry,insurance_expiry:i.insuranceExpiry,is_active:i.isActive}).returning('id').executeTakeFirstOrThrow();return this.findById(r.id);}
 async update(id:number,i:{vehicleNumber?:string;vehicleTypeId?:number;currentStationId?:number;status?:string;fuelCardNumber?:string|null;registrationExpiry?:string|null;fitnessExpiry?:string|null;insuranceExpiry?:string|null;isActive?:boolean}){const p:Updateable<EMSDB['vehicles']>={updated_at:new Date()};if(i.vehicleNumber!==undefined)p.vehicle_number=i.vehicleNumber;if(i.vehicleTypeId!==undefined)p.vehicle_type_id=i.vehicleTypeId;if(i.currentStationId!==undefined)p.current_station_id=i.currentStationId;if(i.status!==undefined)p.status=i.status;if(i.fuelCardNumber!==undefined)p.fuel_card_number=i.fuelCardNumber;if(i.registrationExpiry!==undefined)p.registration_expiry=i.registrationExpiry;if(i.fitnessExpiry!==undefined)p.fitness_expiry=i.fitnessExpiry;if(i.insuranceExpiry!==undefined)p.insurance_expiry=i.insuranceExpiry;if(i.isActive!==undefined)p.is_active=i.isActive;await this.db.updateTable('vehicles').set(p).where('id','=',id).executeTakeFirst();return this.findById(id);}
}
